# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hat-Trick
email: contato@leandro.io
description: > # this means to ignore newlines until "baseurl:"
  Hat-Trick is a blog by Leandro Alonso, a full stack developer
  based on Belo Horizonte, Brazil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leandro.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: /h3/:title

# Build settings
markdown: kramdown
